name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository }} == 'Anthony-Nicholls/example-dev'
    uses: Anthony-Nicholls/example-utils/.github/workflows/build.yml@main
